# Generated by Django 3.0.7 on 2020-06-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syntagi',
        ),
    ]
