# Generated by Django 3.0.6 on 2020-06-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Syntagi',
        ),
    ]
