# Generated by Django 3.0.7 on 2020-06-23 22:42

import api.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_delete_syntagi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syntagi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('prep_mins', models.CharField(max_length=100)),
                ('directions', models.TextField()),
                ('star_rating', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Nicolas\\Desktop\\syntagium\\backend\\syntagium\\media'), upload_to=api.models.image_directory_path)),
                ('image_url', models.URLField(blank=True, max_length=400, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
