# Generated by Django 3.0.7 on 2020-06-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_syntagi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syntagi',
            name='image',
        ),
        migrations.RemoveField(
            model_name='syntagi',
            name='star_rating',
        ),
    ]
