# Generated by Django 3.0.6 on 2020-06-09 00:08

import api.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200608_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntagi',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Nicolas\\Desktop\\Utilities\\web\\senpai\\syntagium\\backend\\syntagium\\media/api'), upload_to=api.models.image_directory_path),
        ),
    ]
