# Generated by Django 3.0.7 on 2020-06-10 05:56

import api.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200608_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntagi',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='syntagi',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Nicolas\\Desktop\\Utilities\\web\\senpai\\syntagium\\backend\\syntagium\\media'), upload_to=api.models.image_directory_path),
        ),
    ]
