# Generated by Django 3.0.7 on 2020-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200610_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntagi',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
