# Generated by Django 3.0.7 on 2020-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200610_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntagi',
            name='prep_mins',
            field=models.CharField(max_length=100),
        ),
    ]
